name: iOS CI Example

on:
  push
jobs:    
  build:
    runs-on: macOS-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        # - name: CocoaPod Install
        #   run: pod install
        - name: run test
          run: fastlane tests
